name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build exe
        shell: cmd
        run: build.bat
      - uses: actions/upload-artifact@v4
        with:
          name: CtrlV-Paste-Image
          path: dist/*.exe
